name: yarn-workflow
on:
  push:
    branches: [main]
# on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - name: Run install
        uses: bahmutov/npm-install@v1
        with:
          #run: yarn test
          useLockFile: false
          install-command: yarn install --prod --frozen-lockfile --non-interactive
          working-directory: |
            packages/backend/
      - name: Run yarn
          working-directory: packages/backend/
          run: yarn
      - name: Run build
          working-directory: packages/backend/
          run: yarn build
  build:
    runs-on: ubuntu-latest
    needs: build-and-test
    timeout-minutes: 1
    steps:
      -   run: ls -la
      -   uses: actions/checkout@master

      -   run: sudo apt-get install rsync

      -   name: Deploy theme on server
          id: deploy_theme
          uses: Pendect/action-rsyncer@v1.1.0
          env:
            DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
          with:
            flags: '-avc --delete'
            src: 'dist/'
            dest: 'root@"${{secrets.SERVER_IP}}":/root/dist/atr-notifier'

      -   name: Display status from deploy
          run: echo "${{ steps.deploy.outputs.status }}"

